# Promtail configuration for BioOps log shipping
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: bioops
    batchwait: 1s
    batchsize: 1048576
    backoff_config:
      min_period: 500ms
      max_period: 5m
      max_retries: 10

scrape_configs:
  # BioOps application logs
  - job_name: bioops
    static_configs:
      - targets:
          - localhost
        labels:
          job: bioops
          app: bioops
          environment: production
          __path__: /var/log/bioops/*.log
    
    pipeline_stages:
      # Parse JSON logs
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            function: function
            analysis_id: analysis_id
            pdb_1_id: pdb_1_id
            pdb_2_id: pdb_2_id
            duration_seconds: duration_seconds
            error_type: error_type
      
      # Set timestamp from parsed JSON
      - timestamp:
          source: timestamp
          format: RFC3339
      
      # Set log level as label
      - labels:
          level:
          logger:
          analysis_id:
      
      # Filter out debug logs in production
      - match:
          selector: '{level="DEBUG"}'
          stages:
            - drop:
                older_than: 24h
      
      # Extract metrics from logs
      - metrics:
          analysis_duration:
            type: Histogram
            description: "Analysis duration in seconds"
            source: duration_seconds
            config:
              buckets: [0.1, 0.5, 1, 5, 10, 30, 60, 300, 600, 900]
          
          analysis_count:
            type: Counter
            description: "Total number of analyses"
            config:
              match_all: true
              action: inc
          
          error_count:
            type: Counter
            description: "Total number of errors"
            source: error_type
            config:
              match_all: true
              action: inc

  # Analysis logs
  - job_name: analysis
    static_configs:
      - targets:
          - localhost
        labels:
          job: analysis
          app: bioops
          __path__: /var/log/bioops/analysis.log
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            step: step
            tool: tool
            status: status
      
      - timestamp:
          source: timestamp
          format: RFC3339
      
      - labels:
          step:
          tool:
          status:

  # Performance logs
  - job_name: performance
    static_configs:
      - targets:
          - localhost
        labels:
          job: performance
          app: bioops
          __path__: /var/log/bioops/performance.log
    
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            function: function
            duration_seconds: duration_seconds
            memory_mb: memory_mb
            cpu_percent: cpu_percent
      
      - timestamp:
          source: timestamp
          format: RFC3339
      
      - labels:
          function:

  # Error logs
  - job_name: errors
    static_configs:
      - targets:
          - localhost
        labels:
          job: errors
          app: bioops
          severity: error
          __path__: /var/log/bioops/errors.log
    
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}'
          max_wait_time: 3s
      
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) - (?P<logger>\S+) - (?P<level>\S+) - (?P<message>.*)$'
      
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'
      
      - labels:
          logger:
          level:

  # Nginx access logs
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          app: bioops
          __path__: /var/log/nginx/access.log
    
    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>\S+) - (?P<remote_user>\S+) \[(?P<time_local>[^\]]+)\] "(?P<method>\S+) (?P<path>\S+) (?P<protocol>\S+)" (?P<status>\d+) (?P<bytes_sent>\d+)'
      
      - labels:
          method:
          status:
      
      - metrics:
          http_requests_total:
            type: Counter
            description: "Total HTTP requests"
            source: status
            config:
              match_all: true
              action: inc
          
          http_request_size_bytes:
            type: Histogram
            description: "HTTP request size in bytes"
            source: bytes_sent
            config:
              buckets: [100, 1000, 10000, 100000, 1000000]